### ISSUE TITLE
Improve late game for garden

### ISSUE THREAD

**Issue by prinzstani** [prinzstani/CookieBot#12]
Currently, the garden is used to produce sugar lumps by sacrificing the garden whenever possible. However, the garden could also be used to boost cps - for example when we have enough sugar lumps.
This needs to be implemented.
In this context, also an appropriate handling at night is needed (currently the garden is frozen at night).

**Comment by prinzstani** [comment]
It pays to continue producing sugar lumps in the garden, as they can be used for the Sugar frenzy and also to reload the spells in order to conjure baked goods.

**Comment by zvei** [comment]
Do you have any future plans that you want to put into the bot.
For example it's efficiency.

**Comment by prinzstani** [comment]
Yes, I am working on efficiency at the moment, but with low priority.

**Comment by zvei** [comment]
What have you placed on a high priority

**Comment by prinzstani** [comment]
Nothing related to the bot.

**Comment by zvei** [comment]
Have you any plans for the late game?

**Comment by prinzstani** [comment]
I have already implemented a garden strategy for the late game. I might work a bit more on having bakeberries when you do not have to harvest sugar lumps. Bakeberries give cps already as such, and then they also give extra results when harvested during a high-value cps time (several active buffs).
