### ISSUE TITLE
Suggestion - manual night mode

### ISSUE THREAD

**Issue by matejur** [prinzstani/CookieBot#14]
I think that there should be a button or something to activate the night mode earlier (even a console function or setting a variable can do the trick).

This comes in handy if i have to turn off my PC before 23h, but still want to get all the CPS benefits of the night mode (like switching the golden switch and temple¸ spirits).

If there is already an option like this (and i just didn't find it), i'm sorry for bothering you.

**Comment by prinzstani** [comment]
This will be solved in the context of #1 Options for Cookie Bot. Still work in progress.

**Comment by prinzstani** [comment]
Added in the beta - will be available in the release soon.
