### ISSUE TITLE
Add more detail to seasons acheivement

### ISSUE THREAD

**Issue by asphaltbuffet** [prinzstani/CookieBot#16]
Status only notes that the bot is waiting for all achievements for Christmas (for example). It's not clear what exactly it's waiting for.

Potentially, if hover on version number showed progress as is, then maybe a more detailed status could be shown when the version number is clicked.

**Comment by prinzstani** [comment]
There is a problem in the current release that the bot is showing it is waiting for christmas results when it is just enabling christmas for performance reasons. This is fixed in the beta and will be available in the release soon.
