### ISSUE TITLE
Users to be able to choose what achievements the bot should aim for

### ISSUE THREAD

**Issue by TheEmbracedOne** [prinzstani/CookieBot#17]
Would be nice if:
- users could select what achievements the bot should aim for
and/or
- disable the bot from pursuing certain achievements

For example I am running into this situation where the bot is doing the following:
- get every halloween themed cookies
- Waiting all results in halloween
- popping wrinklers for droppings and/or achievements
- trying to get plant Elderwort on sector middle

Unfortunately, the only one of of these that the bot is really pursuing is the last one, because it appeased the grandmatriarchs and when I revoke the Elder Covenant it immediately repurchases the "appease grandmatriarchs" switch.

Earlier something similar happened - after the bot acheived the "reach a covenant with the grandmatriarchs", it was pursuing the "get every halloween themed cookies" achievement, however this was my first playthrough a few days ago. I had to disable the bot, ascend, select the season switcher then reenable the bot so it could actually pursue this task, but even then, it went for Christmas, then Love, then Easter cookies before even attempting Halloween. 

To prevent the bot from getting stuck or to be able to direct it at specific achievements, it'd be nice if there was a way to set it to pursue or prevent it from pursuing a specific one.

**Comment by TheEmbracedOne** [comment]
Now that I manually achieved the "halloween results" the bot has been waiting for, it is now going for "100 ascends" but every time it does it it starts it with no bonuses from ascension (otherwise I immediately have billions of CpS), so its very slow. I tried disabling it, doing ascension in a way that my bonuses are active but 1 sextillion in (approx 10 secs into the game) the bot ascends then restarts the game with no bonuses.

**Comment by prinzstani** [comment]
That might be tricky as the bot is often doing several things in parallel. I have to think about it. Currently, the note is saying what the bit is doing, such that you are not too surprised.
As far as the 100 ascends is concerned, this seems to be a bug. It should not start without bonuses. Can you provide me with an export save of the problem situation?

**Comment by TheEmbracedOne** [comment]
Sure thing. I managed to reproduce this issue here:

Mi4wMTA2fHwxNTMyNTExNjk2NTY5OzE1MzE4NTc2NzE0NTU7MTUzMjUxMTcxMDQyNjtBdXRvbWF0ZWQgRmFudGFzdGljIEJpc2N1aXQ7eHlldGx8MDAxMTAxMDAxMDAwMTExMDB8MjUuODEwMDAwMDAwMDAwMDk7MzI4LjgwOTk5OTk5OTk5ODY7MzI3OzE0ODY7MzI3OzU1Mjs0OzIyOzMuOTgzODY0MTM4NTgyNDg3NmUrMzI7MDswOzA7MDswOzI7MDswOzA7MDswOzA7MDs7MDswOzczNTgxNDI7NDU4OTs3MzUzNTUzOzA7MTsxODg7MzIyOzQxOTs1Mjs1MzswOzA7MDswOzUwOzA7MDsxOzEyOzE1MzI0NDIwNjczNzQ7MDswO3wyLDIsMSwwOzAsMCwwLDA7MCwwLDAsMywxNTMyNTExNjk2NjA5OjA6MTUzMjUxMTY5NjYwOTowOjA6OTg6MDowOiAxMTExMTAxMDAwMDAxMTAwMDAwMDAwMDEwMDAwMDAwMDAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MTowOjE6MDoxOjA6MDowOjA6MDowOjA6MTowOjE6MDoxOjA6MDowOjA6MDowOjA6MTowOjE6MDoxOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwxLDgvLTEvLTEgMiAxNTMyNTExNjk2NjExIDA7MCwwLDAsMSw1IDAgMCAwOzAsMCwwLDE7MCwwLDAsMTswLDAsMCwxOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7fDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTAxMTAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTEwMDExMDAxMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTEwMTExMTExMDExMTExMTAwMDAwMDAwMTExMTAxMDAwMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTExMTExMTExMTExMTExMTExMTEwMDAxMTExMTExMTExMDAxMTEwMTEwMTExMTExMTAwMDAwMDExMDEwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTEwMDAxMTAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMHw%3D%21END%21

**Comment by prinzstani** [comment]
I fixed the 100 ascend problem in beta, together with some rewording of the bot strategy.
The bot is not thought to be programmable, so selecting the next step is not an option.
However, it should not be possible to run into the problem with the appeasing, so I will look into this.

**Comment by prinzstani** [comment]
The problem with appeasing is fixed now.
When there are problems because you mixed up things because you bought something strange, then your best bet is to ascend - after that the bot will work correctly again.
