### ISSUE TITLE
Uncaught TypeError: Cannot read property 'won' of undefined

### ISSUE THREAD

**Issue by skokunfloek** [prinzstani/CookieBot#19]
Hello,

When starting the bot in chromium on a raspberry pi I started getting some errors after you beautified the code. Most of them have been resolved already, but the one below still exists for me today.

The bot still appears to be running but the ''(with autoplay v.2.016)'' doesn't appear in the bottom and I can't view the current status of the bot.

Uncaught TypeError: Cannot read property 'won' of undefined
    at Object.AutoPlay.findNextAchievement (<anonymous>:1113:65)
    at <anonymous>:1452:10

Should you need additional information please let me know.

Love the bot btw. Have been running it for over 4 months now without a problem. Keep up the good work.

Skokunfloek

**Comment by prinzstani** [comment]
I think it is fixed now.
