### ISSUE TITLE
Bot gets stuck attempting to get 'ascending with exactly 1 trillion cookies' achievement

### ISSUE THREAD

**Issue by g0dd0gg0** [prinzstani/CookieBot#20]
I've attempted this a few times, and the bot appears to be getting stuck in the 10k to 30k mark after reaching 1 trillion. It keeps fluctuating within those figures, and no progress is made any further. It buys 22 cursors, sells 11 then sells the remaining 10. I've tried ascending a few times to reset it, but it just keeps getting stuck in that specific spot for some reason. Is this supposed to happen?
I run it with cookie monster, if that helps, and I'll add my save file so you can take a look if needed.

`Mi4wMTZ8fDE1NDE0MjEyMjU4NTA7MTQ5ODM3NTE3MjM0MzsxNTQxNDI0NDMzMTcyO0F1dG9tYXRlZCBKYWRlO3Jud2tzfDExMTExMTAxMDEwMTExMTAwMTAxfDEwMDAwMDAwMjc2MzguMzc0NjsxMjE4NDI0NzA0MzQwLjc5MjI7MDsxNjMxMTswOzc4MDU7NDsxMjs1LjQ5NDcxNTU3NjkzNjM0NGUrNDk7MDswOzA7MDstMTsxMjU7MDswOzA7MDswOzA7MDs7MDswOzM4MDE3MzQxMDYyNTQ7Mjc5NjgwOTU4NTcxMzsxMDA0OTI0NTIwNTQxOzA7MDs0OTc7NDk0OzQ5MzsyMjY7NzI7MDswOzA7MDs1MDswOzA7Mjk7MTM3MzsxNTQxMzQ5NzI2MjE0OzE1NDExNjAwMjM5OTM7MTs7fDAsMjgzOTQsMjU0OTgzNSwxNSwsMDswLDc2LDY2NDQ3MzQ5NDcsMTAsLDA7MCw2NiwyNzExMTM5NTkyLDE1LDE1NDE0MjQ1OTIyMTM6MDoxNTQxNDIxMjI1ODY0OjA6MDoxMDI4OjA6MDoxNTQxNDIxMjI1ODY0OiAxMTExMTAxMTExMTExMTEwMTExMTEwMTExMTAwMTEwMTAwIDA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOiwwOzAsNTYsOTY5ODE4ODk1NCwxMCwsMDswLDQ2LDIwNDc2NjIyNjk5LDEwLCwwOzAsMzgsODExNjc0MjA4NDcsMTAsLDA7MCwzMSwzMjAxMTAyNTQ2NDEsMTUsLTEvLTEvLTEgMyAxNTQxNDIxMjI1ODY1IDAsMDswLDIxLDI3MDM2MTg2NDY5MCwxNSw0MCAwIDEwODcgMCwwOzAsMTEsMzUxNjQyNzk4OTcyLDEwLCwwOzAsMSwxNTU2MDkxMjkxNTksMTAsLDA7MCwwLDAsMTAsLDA7MCwwLDAsMTAsLDA7MCwwLDAsMTAsLDA7MCwwLDAsMTUsLDA7MCwwLDAsMTUsLDA7MCwwLDAsMTUsLDA7fDEwMTAxMDEwMTAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDAwMTAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMDAxMTAwMDAwMDAwMDAwMDEwMTAxMDExMTExMTAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDExMTAwMDAwMDAwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDEwMTAxMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMTExMTExMDAwMDAwMTExMTExMDAwMDAwMTExMDAwMDAwMDAwMTExMTEwMTExMTExMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMTAxMTEwMTExMTExMTExMTAwMTAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTAxMTExMTExMTAwMDAxMTAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAxMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTAwMDAwMDAwMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAxMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTEwfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMXw%3D%21END%21`

**Comment by prinzstani** [comment]
OK, I have to fix this. For the moment, you can just buy 100 cursors, which should bring it out of the loop.

**Comment by g0dd0gg0** [comment]
Thank you!

**Comment by prinzstani** [comment]
fixed with new release.
