### ISSUE TITLE
Bot gets stuck attempting to get `go for 1000 ascends`

### ISSUE THREAD

**Issue by LukasMadzik** [prinzstani/CookieBot#21]
With savefile 
[AutomatedgMcPancakeBakery.txt](https://github.com/prinzstani/CookieBot/files/2574142/AutomatedgMcPancakeBakery.txt) bot gets stuck and spamming console with exception `Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'autoplayLog' exceeded the quota.`
Using v. 2.016 with autoplay 2.016

**Comment by prinzstani** [comment]
Fixed with beta.
Please note that this is basically your own problem as you do not have enough space.
You can fix it easily with Options->Clean Log
