### ISSUE TITLE
Ascend for lucky payout

### ISSUE THREAD

**Issue by ProDjMx** [prinzstani/CookieBot#22]
The bot keep ascending and gives me this message: "Ascend for lucky payout"
I'm not sure what is the goal as there is no such achievements, so it keeps ascending every 2 minutes.

**Comment by prinzstani** [comment]
The bot tries toget the heavenly upgrade "lucky payout". In order to match the requirements, the bot tries to limit the prestige level speed by ascending.

**Comment by Jamdog** [comment]
I am also suffering from this issue.  I fail to see how this would limit the prestige level speed...?  Surely each time it ascends, it increases the overall prestige level, causing it to go faster and faster...?

It needs to ascend with a prestige level of 777,777, but is ascending every 2 minutes or so, with a pitifully low prestige level, usually between 50 and 200 - nowhere near the 777k required.

I already have an overall prestige level of over 11 billion, so reaching 777k happens quite fast - why can't the bot just let it get to the right number before ascending...?

![image](https://user-images.githubusercontent.com/94101/50012805-85948000-ffb7-11e8-9057-4647db745888.png)

**Comment by prinzstani** [comment]
It needs to ascend such that the prestige level has 777777 at the end. It cannot do this in one step, it has to approach the 777777 gradually, as the prestige level increase faster and faster the more you have of them. The bot does not stand a chance to ascend just at the right number.
Please try to switch off small numbers (in the options), and then check the current last six digits of your prestige level. The bot is not trying to ascend whenever the distance to the 777777 is halved. When you are currently at 777111, it will ascend somewhere around 333. This distance gets smaller and smaller until the bot reaches 777777. Give it some time and enjoy watching.
If this still does not work for you, please send me a save of your situation.

**Comment by Jamdog** [comment]
Thanks for the explanation - I understand better now what it was doing. And yes, as it got close to it's target, it was ascending more and more often, as the image below shows, taken shortly after my post above.  After this, it ascended again at level 2, then level 1, then stopped ascending, and has now returned to a more normal gameplay.
![image](https://user-images.githubusercontent.com/94101/50037435-062f9c80-0009-11e9-8556-267991d0bf2b.png)
