### ISSUE TITLE
Arcane Sugar isn't normally assignable as permanent upgrade

### ISSUE THREAD

**Issue by PeterRed4091** [prinzstani/CookieBot#23]
Spotted in Cookie Clicker v2.016 beta, with Cookie Bot v2.016 beta
In this version, research upgrades cannot be selected for permanent upgrade slots anymore.
Cookie Clicker's v2.016 live version also has this behavior.
This means buying Arcane Sugar to be saved into such a slot (as stated in the FAQ) is probably no longer meaningful.
Attached is a save file in which Arcane Sugar has been bought for your convenience.
[AutomatedPeterRedBakery.txt](https://github.com/prinzstani/CookieBot/files/2723279/AutomatedPeterRedBakery.txt)

**Comment by PeterRed4091** [comment]
Okay, after a recent ascension, I noticed the bot has no issue assigning Arcane Sugar via code.
Changed the issue to a slightly different problem: should we still make the bot do so if it's not normally possible in the game?

**Comment by prinzstani** [comment]
Removed assigning arcane sugar in the beta.
