### ISSUE TITLE
CookieBot is outdated, please update for v2.018!

### ISSUE THREAD

**Issue by programmer588175** [prinzstani/CookieBot#26]
On the live version, Cookie Clicker has updated to 2.018. CookieBot is therefore out of date until you update this. I use this all the time 😭  so I guess I'll have to stop until you update this. Also no up-to-date bots exist (they added the new version to the beta yesterday and to the live 10 minutes ago as of the time I wrote this)

**Comment by jpchow26** [comment]
FWIW cookie bot seems to be working okay with the recent additions in 2.018. Granted it hasn't done the two heavenly upgrades yet, but it is autobuying the new cookies.

**Comment by jpchow26** [comment]
I take that back... it seems now the cookie auto buying is broken after I ascended and it auto claimed the two new heavenly achievements.

**Comment by jpchow26** [comment]
nevermind.. seems to be working fine. I think it was just trying to get a weird achievement that I wasn't aware of at the time.

**Comment by prinzstani** [comment]
The bot worked already almost correct with the new cookie clicker version.
Now the last bit is also implemented and the bot should handle the complete game.
Still in the beta - will be released soon.
