### ISSUE TITLE
bot not starting up.

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [prinzstani/CookieBot#28]
i tried normal version and beta on a clean save and on a advanced save with like 10 grandmas still not starting up.

**Comment by prinzstani** [comment]
I need some more information to handle this problem. Can you provide me with an exported save of the situation in question?

Here is in any case a short description of how to use the bot:
1) start running cookie clicker.
2) start the bot using the description [here](https://github.com/prinzstani/CookieBot)

Please note that the bot does not read any saves of cookie clicker, it only runs in parallel to a running cookie clicker. The save and restore handling is done with the normal cookie clicker.

**Comment by xXxAaRkEtxXx** [comment]
it needs 16 cookies to start. i forgot about this issue. closed
