### ISSUE TITLE
Bot doesn't click cookie on fresh save

### ISSUE THREAD

**Issue by leo60228** [prinzstani/CookieBot#29]
Is it just trying to get True Neverclick, or is this a bug? The FAQ implies that it would be going for normal Neverclick, not True Neverclick. "Step 1: keep quiet until hardcore and neverclick, then buy everything until all grandma achievements are there, maybe get the first permanent slot with maximum cursors: this takes about 6 days."

**Comment by leo60228** [comment]
I clicked the cookie and it started clicking. I assume it was trying to get True Neverclick and noticed that this was impossible; either documenting this or adding an "ignore Neverclick/Hardcore" option would be nice.

**Comment by prinzstani** [comment]
This is correct, the bot is going for true neverclick first. If not possible, it takes simple neverclick.
When neverclick or hardcore is not possible, the bot is working just fine.
The bot is showing in its status what is happening.
