### ISSUE TITLE
not buying upgrades

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [prinzstani/CookieBot#30]
he cant buy upgrades

**Comment by prinzstani** [comment]
You need to me more specific - what version do you use, do you have a save, how far has the bot come?
At some point in time the bot does not buy upgrades in order to get the hardcore achievement.

**Comment by xXxAaRkEtxXx** [comment]
i use beta version and normal version, the bot never buys achievements... even after 5 hours

**Comment by xXxAaRkEtxXx** [comment]
oh and it was a fresh start

**Comment by prinzstani** [comment]
After a fresh start, the bot tries to get the achievements that are based on not buying anything and not clicking anything (true neverclick and hardcore). Therefore the bot does not buy anything. When the bot comes over the limit for hardcore, it will start buying.
