### ISSUE TITLE
Bot Wont Ever Ascend. (yes i have another issue for you)

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [prinzstani/CookieBot#31]
![image](https://user-images.githubusercontent.com/38191020/56965669-75e09700-6b66-11e9-8d9a-3b94b97acd39.png)
i got up to 5000 ascend levels *i think*
photo is from 5 minutes ago

**Comment by xXxAaRkEtxXx** [comment]
i use beta version

**Comment by xXxAaRkEtxXx** [comment]
update: 
![image](https://user-images.githubusercontent.com/38191020/56965944-de2f7880-6b66-11e9-8f6d-9b2d6db669e7.png)

**Comment by prinzstani** [comment]
You have to wait a bit longer. The bit tries to start the grandmother research, see https://cookieclicker.fandom.com/wiki/Grandmatriarch

**Comment by xXxAaRkEtxXx** [comment]
i have waited about 5 hours

**Comment by prinzstani** [comment]
The first stage of the bot until the first ascend takes about one day.
Do you have already "seven types of upgraded Grandmas"?

**Comment by xXxAaRkEtxXx** [comment]
i dont know it never upgrades

**Comment by prinzstani** [comment]
Please do "Options->Export Save", <ctrl>-C and paste the text into your next answer.

**Comment by prinzstani** [comment]
Closed because it seems this is just a feature and not a bug.
