### ISSUE TITLE
Buying buildings after ascend

### ISSUE THREAD

**Issue by prinzstani** [prinzstani/CookieBot#34]
I have noticed that the bot is awfully slow to buy buildings when it is started some time after the ascend. handleBuildings tries to byu much in the first 10 minutes after ascend, but later it drops to buying 1 at a time, which takes looong time when you want to come up to 500 or more. 
We could buy 100 items at a time whenever it is possible to buy 100 of the most expensive building. In a similar way, we can also buy 10 items at a time whenever it is possible to buy 10 of the most expensive buildings.

**Comment by uecasm** [comment]
I haven't looked at the exact differences, but I've noticed that when I have Cookie Monster loaded at the same time, the bot doesn't buy the buildings that it recommends as the most efficient, but often waits until it can afford a different building.  Not sure who is "right" in these cases.

**Comment by prinzstani** [comment]
That is probably true, as the decision for the bot is very simple. Not sure that it pays to make it more detailed.

**Comment by prinzstani** [comment]
fixed with 2.027
