### ISSUE TITLE
Hard ascend timer gets confused by being suspended

### ISSUE THREAD

**Issue by uecasm** [prinzstani/CookieBot#35]
### ascend after 12.326822326388887 days just while waiting for next achievement.

Not 40 like it's supposed to.  I haven't looked too closely at the cause but I'm fairly sure that the trigger is suspending/hibernating the PC with the browser tab still open.

**Comment by prinzstani** [comment]
Could you give a bit more details what you did?
Please note that the hard ascend timer depends on the ratio of current and new prestige level. If there is a lot of new prestige in relation to the old prestige, then the hard ascend is reduced. For example, when you have as much prestige now as you would get when ascending, then the hard ascend is only 50%, i.e. 20 days.

**Comment by uecasm** [comment]
These are not precise numbers as it's from memory, but as I recall it was showing "still 36 days until next hard ascend" and then I hibernated my PC for two days, and after waking it up again it said "still 25 days until next hard ascend".  Repeat several times, with similar drops each time.

Although it is possible it decided to do it early for prestige.  At that point there were a trillion prestige levels pending.  It's likely that this 50% drop is what kicked in right at the end -- I went to bed (leaving the PC on) with "5 days until next hard ascend" and woke up to find that it had already ascended (after 12 days total, as shown above).

Not a big deal, just a bit peculiar.

**Comment by prinzstani** [comment]
Yes, you are right. The hard timer is dependent on the relative prestige level, which essentially means that the days become 'shorter' when the prestige level is relatively high. This means 2 days of hibernate might bring you some 6 days closer to the ascend. This effect is most visible in the early days of grinding. Without hiberating, it is not much visible.
I agree that it is a bit peculiar, but not big enough for me to work with it ...

**Comment by uecasm** [comment]
Ok, we'll call it "by design" then. :)
