### ISSUE TITLE
Why not to keep "Lucky!" cookies required at max

### ISSUE THREAD

**Issue by helpergandalf** [prinzstani/CookieBot#4]
I am new to cookieclicker.
Why the bot does not consider "Lucky!" cookies required when playing auto mode?
It may try to keep cookies at the bank at top level even after buying. In my opinion, if it does it may reduce time to finish game.

**Comment by prinzstani** [comment]
In principle this is true. In particular, that might help in the speed baking.
However, there are two reasons that this is not considered in cookie bot.
(1) The lucky cookies are quite weak in comparison to the other golden cookies, so their effect does not make too much of a difference.
(2) The time to finish the game is most heavily determined by the sugar lumps, and the speed of getting cookies is not too relevant. There are quite a few achievements that you do not have yet when you have all the cookie related ones, so it is not too important to be quick in getting cookies.
