### ISSUE TITLE
Underperformance to the max

### ISSUE THREAD

**Issue by CJMoseley** [prinzstani/CookieBot#41]
It attempts to ascend before even 1 heavenly chip, therefore killing all progress towards the first PRODUCTIVE ascension. And it doesn't take into account what's actually going to pay itself off fastest, resulting in buying grandmas, when it's going to be faster and more efficient to buy a farm. So there. Food for thought. Because if a human can outpace a bot without full cheating, then something is wrong.

**Comment by prinzstani** [comment]
Hi there,
could you give some more hints about the situation you are in?
Is it the early game or later on?
Which version are you using?
What does the bot say it is currently doing?
Can you provide a game save?
