### ISSUE TITLE
Support for clicking new Fortune upgrades in news ticker.

### ISSUE THREAD

**Issue by jpchow26** [prinzstani/CookieBot#45]
2.021 of CC now has fortune upgrades once the fortune cookie heavenly upgrade is bought. I had a fortune appear in my news ticker and I had to click it manually. 

I'm not certain if clicking the news ticker will generate these fortunes or if it's only on automatic roll over.

**Comment by PrinzAndreas** [comment]
2.021 of CC is still work in progress.

**Comment by DarkPulse** [comment]
As far as I know, they will only appear on automatic cycling, and manually clicking the ticker to change the fortune will result in them never appearing as the next item.

They are easily identifiable due to the fortune cookie icon and the green text though.

**Comment by vern1701** [comment]
Is 2.021 still in beta?  I ask because 2.022 is the live branch of CC. To be fair, I have two saves.  One that uses the bot and one that doesn't.  Can I use the 2.021 beta with 2.022?

**Comment by prinzstani** [comment]
The saves should work for both of them. The bot is good for both of them, but still not complete.

**Comment by prinzstani** [comment]
Fortune cookie clicking is now part of the cookie bot beta.
