### ISSUE TITLE
Getting the error "reborn mode did not work, retry"

### ISSUE THREAD

**Issue by roboapple** [prinzstani/CookieBot#46]
I have let it retry 3 times now, still getting the same error message.
Anyone know a fix?

**Comment by PrinzAndreas** [comment]
This is not an error, just an information. The bot is probably trying to get the Speed baking achievement, and that might need several attempts.
Just wait until the achievement is ready.

**Comment by prinzstani** [comment]
This is a feature, not a bug. The bot is trying to get some achievement where reborn mode is mandatory, for example speed baking. This can take several attempts. Just wait until the bot fixes this.
