### ISSUE TITLE
Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by damadorPL** [prinzstani/CookieBot#47]
Uncaught TypeError: Cannot read property 'Exponential interest rates' of undefined
    at Object.AutoPlay.bestBuy (cookieAutoPlayBeta.js:388)
    at AutoPlay.run (cookieAutoPlayBeta.js:44)

it repeat with any upgrade

**Comment by prinzstani** [comment]
I cannot see this error when I run the bot. an you provide me with more information? Do you run cookie monster in parallel? Can you send an export save of the problem?

**Comment by prinzstani** [comment]
Seems to be fixed, as there is no more error message here - closing it now.
