### ISSUE TITLE
Krumblor uses wrong aura

### ISSUE THREAD

**Issue by Cetino** [prinzstani/CookieBot#51]
Hi,

I've noticed that krumblor always uses "Breath of milk" but once unlocked "Radiant appetite" would be more efficient.

**Comment by prinzstani** [comment]
As far as I can see, after unlocking it, "Radiant appetite" is used. Then "Breath of milk" goes into the second aura. Can you provide an export save of the problem?

**Comment by Cetino** [comment]
yes, in this save krumblor is able to use Radiant appetite but no second aura wich causes the bot to only use breath of milk.
Mi4wMjJ8fDE1Nzg2MDIxODk0ODE7MTU3Nzk4MTc3MDY2MDsxNTc4Njc5MzAzNjg5O0F1dG9tYXRlZCBNY0Jpc2N1aXQ7cWJzanJ8MTExMTExMDExMDAxMDAxMDAxMDEwfDIuMjI4NDIwNTczNTgxMDU5ZSsyNDsxLjMzOTI2OTc4NTA3MjM4NDRlKzI1OzIzODMyNjsxMDY5OzkuNzQ3MTkwMTY4OTg1MDY3ZSsyNDsxNDswOzA7MS4xMTUzNjk0NzA2NDI2NDQ0ZSsyMjswOzA7MDs2ODs0MzYwODsyOzU1OzA7MDsxNDs3OzI0MjUzNjI7MztlYXN0ZXI7MDswOzIyMzQ7MTE5OzIxMTU7MDswOzA7LTE7LTE7LTE7LTE7MjA7MTswOzA7MTAwOzA7MDsxOzk7MTU3ODY1NTg0MzI5MjswOzA7OzQxOzA7MDt8Mjc1LDM3NSw0MzI5MDIyODA1MDA4NDkxMDAwLDAsLDA7MzMxLDQzMSw1ODQwODYwNjE1ODM0OTUzMDAwMCwwLCwwOzIyMiwzMjIsMTI2MDYzMjU1MTY4MzY0OCwzLDE1Nzg2Nzk1NDM3NjA6MDoxNTc4NjAyMTg5NDg3OjA6Mjo5MjoxOjA6MTU3ODYwMjE4OTQ4NzogMTExMDAwMDAwMDAwMTEwMDAwMDAwMDAxMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoyOjkwOjA6MDowOjA6MDowOjA6MDowOjA6MzoyMzowOjA6MDowOjA6MDowOjA6MDowOjI6OTA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMDsyMTQsMzE0LDQyNzUxODYyMDY3ODIyNjAsMCwsMDsxODgsMjg4LDgyNzQyMTg4MDQ0NzY2MzQsMCwsMDsxNzMsMjc0LDM1NTgyNDkyNzk0MDUzNjMwLDAsLDA7MTYwLDI2MCwxNjgzMjU0NzkyOTk1MDgxMzAsMSw4LzEvNiAzIDE1Nzg2NzgzNjgxMDAgMSwwOzEzNSwyMzUsMzcyMjc2ODA2Mjg1MzQwMzAwLDEsMTcuOTU0MjI5OTY2MDY4MTk4IDQgMjUgMSwwOzEyNSwyMjUsMTkwMTc5ODY4MzI1OTk1MjAwMCwwLCwwOzExOCwyMTgsMTA1MjI4MzYyMzQ5MDgzNTkwMDAsMCwsMDsxMTIsMjEyLDU5MDA5NzY2MDUyODU3NDYwMDAwLDAsLDA7MTA2LDIwNiwyNzgzOTkwMDg1NDU3Njk4NTAwMDAsMCwsMDsxMDIsMjAyLDEuNzEzMTk1NzE3MTMwMTU1ZSsyMSwwLCwwOzk3LDE5NywxLjAxMTAxNzU4NjQ0NjI4NTRlKzIyLDAsLDA7OTMsMTkzLDYuNzQ5ODk2Nzk2NDUyMjI5ZSsyMiwwLCwwOzg1LDg1LDMuMDIxNTUyMjUxNjMyMTY2NmUrMjMsMCwsMDs1OSw3MywxLjMyMjU3NjU3MzY3MDI5ODJlKzI0LDAsLDA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMTExMTExMDAxMTExMTEwMDAwMDAxMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMDAwMTEwMDAwMTExMTExMTExMTExMDAwMDAwMDAwMDAwMTExMTExMTExMTExMDAxMTAwMTExMTExMDAwMDAwMDAxMTAwMTExMTAwMDAxMTAwMDAwMDAwMDAxMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDExMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTEwMDAxMTExMDAxMTAwMTEwMDAwMDAwMDEwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMDEwMTAxMTExMTAxMTExMTEwMDAwMDAwMDAwMDAxMTExMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAxMTExMTAxMDEwMTAwMDAwMDAwMDAwMDAwMDEwMTExMTExMTExMTExMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTAxMTExMTExMDExMTExMTAxMTExMTAxMTExMDAwMDExMTEwMTAwMDExMDEwMDExMTAwMDAwMTExMDExMDEwMTEwMTExMDAwMDAwMDExMDAxMTAxMDAwMDAwMTExMTAwMDExMDAxMTExMTAxMTExMDExMTAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTEwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAxMTAxMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDExMTAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAxMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHw%3D%21END%21

**Comment by prinzstani** [comment]
I see. I have fixed it now with the current beta.
