### ISSUE TITLE
Option to enable the bot to work 24/7

### ISSUE THREAD

**Issue by Kikithecat12345** [prinzstani/CookieBot#53]
I may be blind and this is already a thing, but can you add a feature to disable the bot not doing anything during night hours?

**Comment by prinzstani** [comment]
You can go to Options in order to influence what the bot does at night. 
I will add some text about this in the FAQ.

**Comment by Kikithecat12345** [comment]
What exactly do the options mean in night mode? Just asking so I don't have to wait for the FAQ to be updated.

**Comment by prinzstani** [comment]
OFF - no sleeping at night, ON - always sleeping at night, AUTO - bot decides whether to sleep or not.
