### ISSUE TITLE
Getting "Lucky Payout" Faster

### ISSUE THREAD

**Issue by Kikithecat12345** [prinzstani/CookieBot#54]
Would it be possible to control the amount of prestige levels that you get to make getting Lucky Payout much faster?

**Comment by prinzstani** [comment]
Yes, that would be possible, but I do not see why this is a good idea. I feel it is not worth it. Currently, it is purchased before starting with the grinding. It is not really needed before that.

**Comment by Kikithecat12345** [comment]
My problem was that the bot was set to maximum cheating, and by the time it bought all of its towers and upgrades and stuff it would ascend with a practically randomized prestige level. This meant that the bot would reincarnate and repeat until it by chance ascended with a level that ended with 777,777 to buy the upgrade.

**Comment by prinzstani** [comment]
I see. It seems that the manual settings for the bot do not work well together with the auto procedure. Will have a look at this, but not urgently.
Please note that the bot will anyways ascend several times before matching the 777.777. Here the worst that can happen is that the bot goes over the top, and then has to restart. As soon as the bot comes closer to the limit, the better it will work even with much cheating.

**Comment by roncli** [comment]
I am having the same issue, but I do not have cheats turned on.  What's happening is that it creeps up into the hundred decillions/undecillion range, but then something - I can't see what (but it's not a golden cookie) - pops the cookie count well over a duodecillion, usually adding way more than a million prestige to the count and lapping that 777,777 needed.  No idea what's giving such a massive influx, and it happens too fast to see.

**Comment by vanupright** [comment]
Another Problem I have encountered with Lucky Payout is, I never get an odd number of heavenly cookies. The bot can try as hard as he wants, there is always an even number of heavenly cookies. I restarted the game multiple times (4x), had the hope that I will end with an odd number on the count but it always ends up being even.

**Comment by prinzstani** [comment]
This is all fixed with the current version (both beta and regular). Have not tested comprehensively, though.
See also https://github.com/prinzstani/CookieBot/blob/master/FAQ.md#what-is-the-strategy-for-lucky-payout-upgrade

**Comment by prinzstani** [comment]
Seems to work in the tests for several different configurations.
When it starts at a bad stage, then it takes about one hour to step exactly to the right count. 
Does not seem too bad to me.
