### ISSUE TITLE
runJustRight

### ISSUE THREAD

**Issue by BoxDroppingManApe** [prinzstani/CookieBot#57]
I'm having some sort of issue with the script now, and I'm not sure if it's connected to the newest update or not. I'm now getting messages about runJustRight:

`Starting runJustRight`
`runJustRight does not work, retry.`

The bot now seems to be ignoring heavenly chip upgrades, sometimes rapidly buying and selling buildings, and forces ascensions as soon as they are available (even though I alrighty have Reincarnation). The "What is the bot doing?" box just shows "Running just right."

**Comment by prinzstani** [comment]
The bot is trying to get the when the cookies ascend just right achievement, see here: https://www.reddit.com/r/CookieClicker/comments/du4y98/guide_to_when_the_cookies_ascend_just_right/
This does not always work out in the first attempt, then the bot tries once more.
It looks l like it works for me, but please feel free to leave an export save of your situation, such that I can look into your problem.

**Comment by prinzstani** [comment]
fixed with beta 2.029
