### ISSUE TITLE
Black cat's paw

### ISSUE THREAD

**Issue by ELemppu** [prinzstani/CookieBot#6]
The bot seems to get stuck to a loop when it tries to get this achievment where it ascends in born again mode, clicks one golden cookie and repeats. I'm not sure if this is intended but it seems inefficient because the spawning percentage is really low compared to normal ascensions. it shows a debug message after ascending which says, "born again did not work, trying again." Again i am not sure if this is inteded but it seems wrong.

**Comment by ELemppu** [comment]
![1974a55c870f17ff234c4d6ceb9af726](https://user-images.githubusercontent.com/37047282/36948585-a83790c8-1fe5-11e8-8e6e-92eff1e3f894.png)
forgot to add it but here is the curret progression of the bot as far as the achievments go

**Comment by prinzstani** [comment]
That is completely normal in this situation. The bot is trying to get the speed baking III achievement, and this is not easy. So it will try several times until it succeeds. Still working on a better way to show what the current status and plan of the bot are, see #3
