### ISSUE TITLE
Click all cookies during cookie frenzy

### ISSUE THREAD

**Issue by BujuArena** [prinzstani/CookieBot#61]
The bot seems to click fewer than half the cookies during cookie frenzy when it could click all of them.

**Comment by prinzstani** [comment]
I assume you mean golden cookies during the cookie storm. You can enable clicking all those cookies in the cookiebot options by selecting Golden cookie clicking mode = ALL.

**Comment by BujuArena** [comment]
I have it set to "ALL" and it still clicks fewer than half the cookies.  Maybe it's being limited when it could click at 1000 Hz.  I can watch a cookie fade in, stay around for a while, and fade out completely during the cookie frenzy.

**Comment by prinzstani** [comment]
I see, that is unfortunate. Fixed with the current beta, coming to main branch soon.
