### ISSUE TITLE
Cookie Monster purchase integration non-functional

### ISSUE THREAD

**Issue by ChocoboGamer** [prinzstani/CookieBot#62]
When using the bot and enabling the latest version of the Cookie Moster addon. It will only purchase cursors with the money it gains and nothing else, even when another building has a clearly marked better cost-effectiveness. 

You can double-check to make sure this really the issue, but in my limited testing that seems to be the case.

**Comment by prinzstani** [comment]
I have never used or programmed the Cookie Monster addon. Need to wait for someone who is able and interested to do this fix.

**Comment by ChocoboGamer** [comment]
Ah ok, that's reasonable.
I figured I'd report it because it seemed to be on your bot's side, and not Cookie Monster's.
Thank you for the quick responce.

**Comment by Kikithecat12345** [comment]
Closing because it was not autoclosed by PR #87.
