### ISSUE TITLE
What does "Cookiebot global mode" mean?

### ISSUE THREAD

**Issue by unnameable0** [prinzstani/CookieBot#63]
It has 3 options MANUAL, IDLE, and AUTO, but I have no idea how these options function concretely.

**Comment by prinzstani** [comment]
This is a work in progress, related to issue #59 . The general idea is that the AUTO refers to the current operating mode of the bot, while IDLE means to not pursue any goals and just doing the clicking and garden etc. Manual means then to select which goal to pursue. The whole thing is still quite open - I will provide an update when it is more final. Currently, the modes do not work yet.
