### ISSUE TITLE
After reset optimizations

### ISSUE THREAD

**Issue by Buti1986** [prinzstani/CookieBot#64]
I started a new game using the bot to see how it performs now with the market, 100% bot playing, not helping in anyway, so this are some "problems" the bot run in and I think have easy solutions.

- The stock market need a timing before starts to purchase stuff, if the bot starts to purchase stuff at the beggining of the reset it slow down the run a lot, you can't purchase more than 10-15 of each at a time, because you don't have enough cookies, and when the bot wants to purchase like 600 CHC, 555 NUT and 460 CNM for example you have a lot of resources wasted that even can make the bot not having enough to go another season.

Ideally I would not let the bot purchase anything until I have all the easter season and halloween droppings, but a simple "not purchaching the first 3 hours" or something like that, kinda the same you have for saving strategy should work good enough.

- The use of Skruuia, I get why you use Skruuia to speed up the droppings, but I'm not sure if this is necessary or even optimal (maybe only for the first time you are trying to get all the droppings is ok tho) the first easy goals (like from getting to 1 decillion to 1 quattordecillion) I found myself being able to reach the goal in about one and a half or two hours, but after the first hour you get stuck with Skruuia for 2 or 3 hours without any progress, getting the droppings that you don't need to reach the goal, just to change to Mokalsium and reaching the goal after ten minutes.

In any case, the real problem is Skruuia + stock market trying to buy stuff early, I saw the bot stuck for 2 hours with all the easter season eggs, but unable to move to halloween season, because you are spending all the cookies in the stock market before you get enough to buy the new season, and the few times you get a "good" cookie with Skruuia (like elder frenzy) being unable to buy the upgrade because is recalculating how much to save and you spend everything again in the market.

I know these are small problems and for kinda very early gameplay, but at least the market should be easy to put a timer on and make the resets much smoother and even if Skruuia may be optimal it really is very frustrating to watch and should be more pleasant to see regular golden cookies gameplays even if you delay the droppings a bit.

Other than that, the bot is working better than ever, I like a lot more how is playing with the Grimoire now, casting a lot more spells, the only small thing is the saving strategy, sometimes I fell that it should try to go for 100% saving no matter what instead of recalculating so many times how much to save.

**Comment by prinzstani** [comment]
Yes, I agree with most of what you say.
1) The stock market should not exceed the saving limits. Currently, saving is not aligned with the stock market, and it should be.
2) We do not need Skruuia after we had achieved all droppings for the first time. Still, I do not think it is slowing down the process as much as 1) does.

I work on other parts of the bot currently and will mark this issue as beginner issue, so maybe someone comes witha solution.

**Comment by Kikithecat12345** [comment]
@Buti1986 do you think you could provide a save file for which I could test with?

**Comment by Buti1986** [comment]
[SnazzyKittenBakery.txt](https://github.com/prinzstani/CookieBot/files/7874613/SnazzyKittenBakery.txt)


Sadly this is the only safe file that I have at the moment, and is kinda advanced, it may work to test it with just a reset tho, no matter the amount of heavenly chips the start is still a bit slow.
