### ISSUE TITLE
[Steam] Game.UpgradesById.foreach does not work anymore

### ISSUE THREAD

**Issue by Tanzgarnele** [prinzstani/CookieBot#70]
Aparrently the foreach function does no longer work in Steam:
![image](https://user-images.githubusercontent.com/47541889/132362230-95b11214-b241-44cf-af70-621ae1e2d016.png)

I replaced the lines
```
 Game.UpgradesById.forEach(function(e) {
    if (e.unlocked && !e.bought && !AutoPlay.avoidbuy(e))
      AutoPlay.buyUpgrade(e, true);  // checks price, bypass = true
  });
```

with this one
```
for (var e in Game.UpgradesById){
    if (e.unlocked && !e.bought && !AutoPlay.avoidbuy(e))
      AutoPlay.buyUpgrade(e, true);  // checks price, bypass = true
  };
```

it seems to be working again.

Same one for the other foreach lines

**Comment by prinzstani** [comment]
Looks like you have control of the changes needed to make it work for Steam.
Can you merge it into the beta? I can give you collaborator rights or you produce a pull request.

**Comment by Kikithecat12345** [comment]
Has this been fixed yet?

**Comment by prinzstani** [comment]
I think so. At least this line does not appear in the code any longer.

**Comment by Kikithecat12345** [comment]
Can we close this issue then?

**Comment by Tanzgarnele** [comment]
I merged the fix back then.
