### ISSUE TITLE
[Steam] Third-party achievement blocks the steam achievements.

### ISSUE THREAD

**Issue by steinbuck** [prinzstani/CookieBot#72]
Using the bot, I still get the game achievements but can't get the Steam ones. When I deactivate 'Third-party' in the web version and import the save to Steam, the achievements unlock. I believe CookieMonster had the same issue.

**Comment by prinzstani** [comment]
I see. Currently, I do not use Cookie clicker on Steam and I do not plan to do so in the near future. I hope someone can work on this. Let me know when you want to work with these problems, then I can give you access to the repository.

**Comment by Kikithecat12345** [comment]
This is an easy fix: add `"AllowSteamAchievs": 1` to the end of *info.txt*.

**Comment by prinzstani** [comment]
So I think this means we need a file info.txt in git?

**Comment by Kikithecat12345** [comment]
> So I think this means we need a file info.txt in git?

Only if we are compiling for Steam as well. However, it should be considered if the bot is technically cheating or not.

**Comment by prinzstani** [comment]
As far as I can see, this is already in the info.txt in the zip files, so it seems this is fixed.

**Comment by Kikithecat12345** [comment]
If this is fixed, I will close the issue.
