### ISSUE TITLE
[Steam] Easy compatibility with Steam

### ISSUE THREAD

**Issue by thelmexx** [prinzstani/CookieBot#74]
Cookie Clicker mods on Steam appear to be loaded in the form of two files, info.txt (used like a .json file) and main.js, so simply adding these as a release would make super easy for users to install.

mockup info.txt:
```
{
	"Name": "CookieBot",
	"ID": "cookie bot",
	"Author": "prinzstani",
	"Description": "Cookie Bot is an add-on you can load into Cookie Clicker, that will do an automatic playthrough for Cookie Clicker.",
	"ModVersion": 2.030,
	"GameVersion": 2.042,
	"Date": "13/09/2021",
	"Dependencies": [],
	"Disabled": 1
}
```

and main.js works exactly like the js console in browsers:
`Game.LoadMod('https://prinzstani.github.io/CookieBot/cookieAutoPlayBeta.js')`

Not going to make any comment on the morals of it, but you can also re-enable Steam achievements by appending `"AllowSteamAchievs": 1` to the end of info.txt (this fixes #72 )

**Comment by prinzstani** [comment]
I do not intend to handle Steam issues myself, but please create a pull request with the needed changes, and I will accept it and make it into a release.

**Comment by Kikithecat12345** [comment]
> I do not intend to handle Steam issues myself, but please create a pull request with the needed changes, and I will accept it and make it into a release.

[CookieBot Beta.zip](https://github.com/prinzstani/CookieBot/files/7296588/CookieBot.Beta.zip)
[CookieBot.zip](https://github.com/prinzstani/CookieBot/files/7296589/CookieBot.zip)
These 2 .zips are ready-made versions of the mod that auto-update. (like the bookmarklet) They just need to be made into a release.

**Comment by prinzstani** [comment]
I am a bit unsure how to handle this in git. It seems like the zip file is straightforward and does not change lot. We probably should create a folder for all the files (info and js). As we now have the same information several places, we might also start to consider some build script. I do not think we want to deliver the beta in a release - currently only real releases are distributed and beta is the current state. So maybe we provide the beta zip in a folder and the main zip is then released in a git release?

**Comment by Kikithecat12345** [comment]
The steam version has finally gotten Steam Workshop support, would this be a good time to add it there?

**Comment by prinzstani** [comment]
I have added the two zip files into the main bot folder.
Maybe someone could provide an updated description of how to use it in the README.

**Comment by Kikithecat12345** [comment]
> As we now have the same information several places, we might also start to consider some build script.

I can make a quick and dirty node.js build script if that helps.

**Comment by prinzstani** [comment]
After reconsidering, I feel we do not need a build script after all, as the zip files will work independently of the changes in the code. 
The only thing that would be nice is a decent description of using the zip files for Steam.

**Comment by Kikithecat12345** [comment]
I can do that, should I also add the .zip files to the repository? @prinzstani

**Comment by prinzstani** [comment]
The zip files are already there in the main folder. When you add a description we should be done.

**Comment by Kikithecat12345** [comment]
I can also add this to the steam workshop, if you want. This will allow more people to see it, and also make it trivial to install. I want your permission to do this though, @prinzstani

**Comment by prinzstani** [comment]
I understand that this would put the bot into the tools available in Steam.
That sounds like a great idea, just go ahead.
