### ISSUE TITLE
Hacking in cookies Shadow achievement

### ISSUE THREAD

**Issue by zvei** [prinzstani/CookieBot#8]
After you have obtained 1 duodecillion cookies does the bot wait till a certain time to hack in cookies or has this not been implemented?

Here is my save if you wish to test it 

Mi4wMTA2fHwxNTI0NTA0NzA1NTUwOzE1MjI0NDUxODQwOTI7MTUyNDUwNTI1MjcwMDtBdXRvbWF0ZWQgQ2FuYWRpYW5Gcmllczt3ZnpucnwxMTExMTExMTEwMDEwMDExMHwzLjU0NDc0NzUwMjk0ODE3M2UrMzI7OS44NTQ1MDQ4MjA1MTg2NDFlKzMzOzE3MTU7OTE3NTsyLjQ1ODQ5NjA4MzIwNjc3MzRlKzMzOzE1ODsyOzEzOzEuMTkzMTIwNDAyODczOTQ1ZSszOTswOzA7MDs2ODs1Mzg4OzEwNDsxOzA7MDsxNDszOzI1NzU3MzQ7MTtjaHJpc3RtYXM7MDswOzEwNjA2MjM5MzY7Mjg5NzAxNTc7MTAzMTY1Mzc3OTswOzA7NDAwOzQ0Mjs0NDE7MjI2OzcyOzIyOzE1OzE7MDswOzA7MDszOzIyOzE1MjQ0NTkyMTkzNzA7MDswO3w1MDMsODUzLDYuMzMzNDg3MTgxMjM0NTY4ZSszMCwwOzQ1MCw4MDAsNy4zMTU4OTg4OTMyNDExOTFlKzI3LDA7NDI5LDc3OSw0Ljc0NDk3MjM1NTM2MTg3M2UrMjksMSwxNTI0NTA1MzA1OTQ4OjA6MTUyNDUwNDcwNTY5MTowOjA6MDowOjA6IDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6OzQ1Miw4MDIsMi4yNTU3NTIyMTQzNDMzMTVlKzMxLDA7NDM1LDc4NSw1LjkyNDcxNDQyNjk5MzQ1ZSszMCwwOzQwMCw3NTEsMS44MTQ2MTE3MTY1NTI1ODMzZSszMCwwOzQwMiw3NTIsNy42NTgwMTE1NjA0NDI2NTdlKzMwLDEsOC8tMS8tMS8tMSAyIDE1MjQ1MDQ3MDkxOTAgMDszNzUsNzI1LDMuNjA2MjEwMTQ1OTMxNDgxZSszMCw1LDQyLjQyMDAxODkwMzg5Mjk5IDAgNTk3IDA7MzMwLDY4MCwxLjYwMTM5OTIwNDU3MzkxN2UrMzAsMDszMzYsNjg2LDguNDQwODA5NjQwODUyODg1ZSszMCwwOzMyMSw2NzEsNC40NTU5OTEyNzk5ODA0NzFlKzMxLDA7MzA5LDY1OSwyLjUwMzUyNzYzMTkyMjM3NDdlKzMyLDA7MzAzLDY1MywxLjUxOTM1OTcyODcxMjkxMThlKzMzLDA7Mjc4LDYyOSw0LjE4MjYxNTIxOTMwNjA1MWUrMzIsMDsyNjksNjIwLDMuMTUyMTM4ODEwMDQ0OTQzNmUrMzMsMDt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMTEwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTEwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTAxMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTAwMTEwMDAwMTAxMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTExMTExMTExMDAxMTExMTAxMTExMTExMDEwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDExMDExMTExMTExMTExMTAxMTExMTExMTExMTExMTAwMDExMTExMDAwMDAwMDAwMTAwMDAwMDAxMTAwMDAwMTEwMDAwMDAwMTAwfDksMTAyMCw2MzAsNDMuOSwyOw%3D%3D%21END%21

**Comment by prinzstani** [comment]
The hidden achievements are taken in the endphase, here after 350 chancemakers. This is likely to be changed to higher values, as the endphase is later in version 2.01. Everything works fine.
