### ISSUE TITLE
No upgrades?

### ISSUE THREAD

**Issue by Rovey** [prinzstani/CookieBot#82]
I know it doesn't upgrade until it has the hardcore achievement. But after getting that it still didn't purchase any upgrades (now 10 hours after the hardcore achievement). Is it waiting for something else or is there something wrong?

Running autoplay v2.029 with game v2.043 (Steam), everything else seems to be working fine.

Let me know if I'm missing something or if this is just a bug with the latest version, much appreciated!

**Comment by Rovey** [comment]
Seems to be fixed in the beta version though (v2.030).

**Comment by prinzstani** [comment]
OK, I need to do some tests and then make the beta available as the main version.

**Comment by prinzstani** [comment]
Now the beta code is lifted to master and everything should work out. Would need to check with the new cookieclicker version ...
