### ISSUE TITLE
Game version 2.052

### ISSUE THREAD

**Issue by FlamingNinja42** [prinzstani/CookieBot#91]

**Comment by prinzstani** [comment]
It seems the new version is covered very well with the old code already, apart from four achievements.
589 - redeem a cookie gift code
597 - shape your clones to resemble grandmas
598 - poke a wrinkler 50 times without killing it
637 - takeout a loan and ascend before the CpS penalty

I am a bit busy now but will look into it when I have some time.

**Comment by Kikithecat12345** [comment]
Related to #83. We should do both at once.

**Comment by prinzstani** [comment]
> Related to #83. We should do both at once.

Absolutely. Somehow we need to end up in alpha.

**Comment by prinzstani** [comment]
fixed with stable now
