### ISSUE TITLE
Just doesn't work, Not sure what i'm doing wrong 

### ISSUE THREAD

**Issue by Userfound0** [prinzstani/CookieBot#98]
I've tried the browser ver, steam and just cannot get it working, It'll show up the achievements saying "cookiebot" etc and it'll also show up in my options with the different options I can select but they do absolutely nothing, no auto clicking, no buying, and I'm just not sure what I'm doing wrong

**Comment by prinzstani** [comment]
Before we can find out what you are doing wrong, it would help if you tell us what you are doing.
In particular, when the bot is activated and you can see the bot options, then you should be able to send the current tasks the bot is doing. You see this when you hover over the version string.

Please note that the bot IS doing nothing at the beginning of the game as it wants to get the neverclick achievement by not clicking at all. It waits for golden cookies.

**Comment by Userfound0** [comment]
Yea, I'm just stupid don't mind me. thanks for trying to help my stupid ass lmao

**Comment by prinzstani** [comment]
Good, then I close this issue.
